### ISSUE TITLE
No element found for selector: textarea

### ISSUE THREAD

**Issue by deltrexgg** [Parking-Master/node_perplexityai#1]

**Comment by Parking-Master** [comment]
Hello! Make sure you use `await ...` or `.then()` to catch the promise after __node_perplexityai__ is ready. The API is returning this error because it's trying to type in the input box on www.perplexity.ai, but the API is currently not ready.

Please re-open this issue if you get any other errors!

**Comment by deltrexgg** [comment]
const perplexity = require("node_perplexityai");
const prompt = "What is brain";
(async () => {
  const result = await perplexity.send(prompt);
  console.log(result);
})();

Still getting same issue
this was the code

**Comment by Parking-Master** [comment]
Ok, thanks for pasting the code. I'll look into it and see what's causing this issue.

**Comment by Parking-Master** [comment]
Ok, it seems I just need to add a `waitForSelector(...)` in puppeteer before the message is sent. I'll push an update tomorrow and keep you updated!

**Comment by Parking-Master** [comment]
Hey, I've added the waiting function. Could you try a fresh install and restart your script? Thanks!

**Comment by deltrexgg** [comment]
looks like it cant bypass cloud flare

**Comment by Parking-Master** [comment]
Oh yeah, cloudflare updated their bot blockers, I'll have to do a major fix on this. Thanks for your patience, I'll try to fix it ASAP.

FYI This will be easy to fix because I have a personal API for another site using cloudflare, and I've used the puppeteer stealth plugin and mixed in some headers, it worked. I'll just do the same for this.

Check back in tomorrow!

**Comment by Parking-Master** [comment]
Reopening this issue because it's confirmed not working at all. I'll keep you updated

**Comment by Parking-Master** [comment]
Problem fixed. Let me know if you have any more problems.
